config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  devise_for :users
  
  resources :users

  resources :questions do
    resources :comments
  end
  
  resources :comments do
    resources :comments 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  belongs_to :user  
  validates :body, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentsHelper
  before_action :find_commentable
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.new comment_params
    if @comment.save
      flash[:notice] = get_flash_notice
      redirect_back fallback_location: root_path
    else
      redirect_back fallback_location: root_path, :alert => "Your comment wasn't posted!"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body,:user_id)
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Question.find_by_id(params[:question_id]) if params[:question_id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_question, only: [:show]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_user, only: [:create, :edit]
  def new 
     @question = Question.new
  end

  def index
    @questions = Question.all.order(created_at: :desc)
  end

  def create
    @question = @user.questions.new(question_params)
    if @question.save
      flash[:notice] = "Succesfully Posted"
      redirect_to @question

    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @question.update
     redirect_to @question
    else
     render 'edit'
    end
  end
 
  def destroy
    @question.destroy
    redirect_to questions_path
  end
 
  private

  def question_params
    params.require(:question).permit(:title, :description)
  end

  def find_question
    @question = Question.find(params[:id])    
  end

  def set_user
    @user = current_user if current_user
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    questions_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_back fallback_location: root_path, :alert => "Access denied."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def get_flash_notice
    return "Your comment was successfully posted" if @commentable.class == Question
    return "Your Comment Reply was successfully posted" if @commentable.class == Comment 
  end
end

app/views/comments/_comment.html.erb
<div class= 'comment_wrapper'>
  <li>
    <p><%= comment.body %> 
    <div><small>Submitted <%= time_ago_in_words(comment.created_at) %> ago</small> by: <%= comment&.user&.email%> </p></div>
    <h4>Replies:</h4>
    <ul>
      <%= render(partial: 'comments/reply', collection: comment.comments) %>
      <%= render(partial: 'comments/new_reply', locals: {comment: comment}) %>
    </ul>
  </li>
</div>

app/views/comments/_new_reply.html.erb
<%= form_for [comment, Comment.new] do |f| %>
    <%= f.hidden_field :user_id, value: current_user&.id%>
    <%= f.text_area :body, placeholder: "Add a Reply", class: 'form-control form-control-sm', required: true %><br/>
    <%= f.submit "Reply", class: "btn btn-primary" %>
<% end %>

app/views/comments/_reply.html.erb
<li>
 <p><%= reply.body %></p>
 <div><small>Submitted <%= time_ago_in_words(reply.created_at) %> ago by : <%= reply&.user&.email%> </small> </div>
</li>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Questions', questions_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Online Forum" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Online Forum" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css"></link>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <div class="wrapper">
         <%= yield %>
       </div>
    </main>
  </body>
</html>

app/views/questions/_new_question.html.erb
<h3>Add new Question</h3>
<%= form_for [@question] do |f| %>
  <%= f.text_field :title, placeholder: "Add a Title", class:'form-control', required: true%><br/>
  <%= f.text_area :description, placeholder: "Add a Description", class: 'form-control' %><br/>
  <%= f.submit "Post" ,class: "btn btn-primary" %>
<% end %>

app/views/questions/index.html.erb
<div class="new_question_button">
  <%= link_to "New Question", new_question_path %>
</div>

<div class="posts">
  <% if @questions.empty? %>
    Questions will appear here
  <% end %>
  <% @questions.each do |question| %>
    <div class="post">
      <h2 class="title">
        <%= link_to question.title, question %>
      </h2>
      <p class="date">
       <b> Published at:</b>
        <%= time_ago_in_words(question.created_at) %>
        <b>By:</b>
        <%= question.user.email %>
      </p>
    </div>
  <% end %>
</div>

app/views/questions/new.html.erb
<%= render(partial: 'new_question') %>

app/views/questions/show.html.erb
<div class="posts">
  <div>
    <h3><%= @question.title %></h3>
    <b> Submitted:</b> <%= time_ago_in_words(@question.created_at) %> ago <b>by:</b>
    <%= @question.user.email %>
  </div>
  <p>  <b>description: </b>
<%= @question.description %> </p>
</div>

<h3>Comments</h3>

<%= form_for [@question, Comment.new] do |f| %>
<%= f.hidden_field :user_id, value: current_user&.id%>
<%= f.text_area :body, placeholder: "Add a comment", class: 'form-control',  required: true%><br/>
<%= f.submit "Add Comment", class: "btn btn-primary"%>
<% end %>


<ul>
  <%= render(partial: 'comments/comment', collection: @question.comments) %>
</ul>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>